#!/bin/bash -f
#
# nstep = number of cycles
# rho   = density
# ppt   = fraction of exchanges
# ntemp = number of temperatures (systems)

# set nstep = 100000
# set rho   = 2.5
# set ppt   = 0.2
# set ntemp = 6

nstep=1000000
rho=2.5
ppt=0.2
ntemp=6

cat > input << endofdata
Rho  Ppt   Nstep   Ntemp
$rho $ppt  $nstep  $ntemp
Temperatures
0.05 0.025 0.01 0.005 0.0025 0.001
endofdata
../Source/pt
rm input
exit
